import { Router } from "express";
import { FinanceControllers } from "./finance.controller";
import { FinanceValidation } from "./finance.validation";
import validateRequest from "../../middleware/validateRequest";
import { authWorkspace } from "../../middleware/auth";
import { requirePermission } from "../../middleware/workspace";
import { requireFeatureAccess } from "../../middleware/featureAccess";

const router = Router();

// Every finance route requires authentication + an ACTIVE workspace membership.
// Workspace scope is re-derived server-side from memberships — never from the
// client. Write operations are authorised inside the service against the
// TARGET workspace's membership role (the active-workspace role is not enough
// in "All Workspaces" mode); read operations are gated by the active role here.
router.use(authWorkspace() as any);

// Finance WRITES are a premium feature (Free plan does not include it), but
// reads stay open so historical records remain viewable after expiry. Pure
// entitlement check — no usage counting.
const requireFinanceFeature = requireFeatureAccess("finance", {
  trackUsage: false,
  incrementBy: 0,
});

// ── Transactions ─────────────────────────────────────────────────────────────
// There is intentionally NO POST /transactions. Finance income is generated by
// the payment workflow (appointment payment → `recordAppointmentIncome`), so a
// manually-created ledger row would let a user bypass that workflow and desync
// the books from the payments. Ledger rows are read, corrected or removed
// through the routes below; they are never fabricated by hand.
router.get(
  "/transactions",
  requirePermission("finance_view"),
  validateRequest(FinanceValidation.listTransactionsSchema),
  FinanceControllers.listTransactions,
);

router.get(
  "/transactions/:id",
  requirePermission("finance_view"),
  FinanceControllers.getTransaction,
);

router.patch(
  "/transactions/:id",
  requireFinanceFeature as any,
  validateRequest(FinanceValidation.updateTransactionSchema),
  FinanceControllers.updateTransaction,
);

router.delete(
  "/transactions/:id",
  requireFinanceFeature as any,
  FinanceControllers.deleteTransaction,
);

// ── Summary & reports ────────────────────────────────────────────────────────
router.get(
  "/summary",
  requirePermission("finance_view"),
  validateRequest(FinanceValidation.summaryQuerySchema),
  FinanceControllers.getSummary,
);

router.get(
  "/reports",
  requirePermission("finance_report_view"),
  validateRequest(FinanceValidation.reportQuerySchema),
  FinanceControllers.getReport,
);

// ── Categories ───────────────────────────────────────────────────────────────
router.get(
  "/categories",
  requirePermission("finance_view"),
  validateRequest(FinanceValidation.listCategoriesSchema),
  FinanceControllers.listCategories,
);

router.post(
  "/categories",
  requireFinanceFeature as any,
  validateRequest(FinanceValidation.createCategorySchema),
  FinanceControllers.createCategory,
);

router.patch(
  "/categories/:id",
  requireFinanceFeature as any,
  validateRequest(FinanceValidation.updateCategorySchema),
  FinanceControllers.updateCategory,
);

router.delete(
  "/categories/:id",
  requireFinanceFeature as any,
  FinanceControllers.deleteCategory,
);

export const FinanceRouters = router;
